[tool.poetry]
name = "openvpn-cert-gen"
version = "0.1.0"
description = ""
authors = ["dazzgt <dazzgt@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
cryptography = "^46.0.3"
pbkdf2 = "^1.3"
pycryptodome = "^3.23.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
